"""
Shared State Definition for the Agentic Workflow Engine.

This module defines the TypedDict state that flows through the entire
LangGraph workflow. Every agent reads from and writes to this shared state.
"""

from typing import TypedDict, Optional


class AgentState(TypedDict):
    """
    Shared state object that persists across all agent nodes in the workflow.

    Fields:
        user_input: The original natural language task from the user.
        plan: Structured plan generated by the Planner Agent (list of steps).
        tool_selections: Tools selected for each plan step by the Tool Selector Agent.
        execution_results: Results from executing each step via the Executor Agent.
        monitor_feedback: Feedback from the Monitor/Reviewer Agent.
        monitor_decision: 'approved' or 'rejected' — controls conditional routing.
        final_output: The approved final output presented to the user.
        retry_count: Number of retry cycles (max 2).
        agent_logs: Complete log of all agent reasoning and decisions.
    """
    user_input: str
    plan: Optional[list]
    tool_selections: Optional[list]
    execution_results: Optional[list]
    monitor_feedback: Optional[str]
    monitor_decision: Optional[str]
    final_output: Optional[str]
    retry_count: int
    agent_logs: list
