/**
 * PlanDisplay — Shows the structured plan generated by the Planner Agent.
 * Renders each step with number, title, description, dependencies, and expected output.
 */
export default function PlanDisplay({ plan }) {
  if (!plan) return null

  const steps = plan.steps || []

  return (
    <div className="panel" id="plan-panel">
      <div className="panel__header panel__header--planner">
        <span className="panel__header-icon">📋</span>
        <span>Execution Plan</span>
        <span style={{ marginLeft: 'auto', fontSize: '0.75rem', opacity: 0.6 }}>
          {steps.length} steps
        </span>
      </div>
      <div className="panel__body">
        {plan.task_summary && (
          <div style={{ marginBottom: '16px', fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
            <strong style={{ color: 'var(--text-accent)' }}>Task:</strong> {plan.task_summary}
          </div>
        )}

        {steps.map((step, i) => (
          <div
            key={step.step_number || i}
            className="plan-step"
            style={{ animationDelay: `${i * 100}ms` }}
          >
            <span className="plan-step__number">{step.step_number || i + 1}</span>
            <div className="plan-step__content">
              <div className="plan-step__title">{step.title}</div>
              <div className="plan-step__desc">{step.description}</div>
              <div className="plan-step__meta">
                {step.depends_on && step.depends_on.length > 0 && (
                  <span className="plan-step__meta-item">
                    🔗 Depends on: Step {step.depends_on.join(', ')}
                  </span>
                )}
                {step.expected_output && (
                  <span className="plan-step__meta-item">
                    📤 Output: {step.expected_output}
                  </span>
                )}
              </div>
            </div>
          </div>
        ))}

        {plan.reasoning && (
          <div className="plan__reasoning">
            <strong>💡 Planner reasoning:</strong> {plan.reasoning}
          </div>
        )}
      </div>
    </div>
  )
}
